
services:
  api:
    build: .
    volumes:
      - type: bind
        source: ../../
        target: /jobs/
    working_dir: /jobs/02_company
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_ddb
      POSTGRES_HOST: "db:5432"
    ports:
      - 1010:1010
    networks:
      jobs-net:
        ipv4_address: 172.22.0.4
      api-net:
    depends_on:
     - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_ddb
    volumes:
     - pgdata:/var/lib/postgresql/data
     - type: bind
       source: ../../02_company
       target: /jobs/
    networks:
      - api-net
    ports:
      - "1011:1011"

volumes:
  pgdata:


networks:
  jobs-net:
    external: true
  api-net: