
services:
  api:
    build: .
    volumes:
      - type: bind
        source: ../../
        target: /jobs/
    working_dir: /jobs/01_authentication
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_ddb
      POSTGRES_HOST: "db:5432"
    ports:
      - 1000:1000
    networks:
      jobs-net:
        ipv4_address: 172.22.0.3
      api-net:
    depends_on:
     - db
      
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_ddb
    volumes:
     - pgdata:/var/lib/postgresql/data
    networks:
      - api-net
    ports:
      - "1001:1001"

volumes:
  pgdata:


networks:
  jobs-net:
    external: true
  api-net: